services:
  nginx:
    container_name: frigate-nginx
    image: nginx:1.27
    restart: unless-stopped
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ${CERT_DIR:-~/test-cert/}:/certs/:ro
    - /etc/localtime:/etc/localtime:ro
    ports:
    - 65001:443
    networks:
    - frigate
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.1
    shm_size: "512mb"
#    privileged: true
    # https://docs.docker.com/reference/compose-file/services/#device_cgroup_rules
#    device_cgroup_rules:
#      - 'c 51:* rmw'  # Allow access to all /dev/video* devices
    volumes:
 #     - /dev:/dev
      - frigate-config:/config/
      - /etc/localtime:/etc/localtime:ro
      # https://github.com/blakeblackshear/frigate/blob/v0.15.1/frigate/util/config.py#L20
      - ./frigate.yml:/config/config.yaml:ro
      - ./storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 500m
    ports:
      - "8554:8554" # RTSP feed
      # https://docs.frigate.video/configuration/live/#setting-stream-for-live-ui
      - "8555:8555" # WebRTC over tcp/ udp (Tapo C200)
    networks:
      - frigate
    environment:
      # https://github.com/blakeblackshear/frigate/blob/v0.15.1/frigate/config/env.py
      - FRIGATE_RTSP_USER_C200=/run/secrets/FRIGATE_RTSP_USER_C200
      - FRIGATE_RTSP_PASSWORD_C200=/run/secrets/FRIGATE_PASSWORD_C200
      - FRIGATE_RTSP_IP_C200=/run/secrets/FRIGATE_IP_C200
      - FRIGATE_MQTT_USER=/run/secrets/FRIGATE_MQTT_USER
      - FRIGATE_MQTT_PASSWORD=/run/secrets/FRIGATE_MQTT_PASSWORD
    secrets:
      - FRIGATE_RTSP_USER_C200
      - FRIGATE_RTSP_PASSWORD_C200
      - FRIGATE_RTSP_IP_C200
      - FRIGATE_MQTT_USER
      - FRIGATE_MQTT_PASSWORD

networks:
  frigate:

secrets:
  FRIGATE_RTSP_USER_C200:
    file: ${SECRETS_DIR:-}c200-user.secret
  FRIGATE_RTSP_PASSWORD_C200:
    file: ${SECRETS_DIR:-}c200-pw.secret
  FRIGATE_RTSP_IP_C200:
    file: ${SECRETS_DIR:-}c200-host.secret
  FRIGATE_MQTT_USER:
    file: ${SECRETS_DIR:-}mqtt-user.secret
  FRIGATE_MQTT_PASSWORD:
    file: ${SECRETS_DIR:-}mqtt-pw.secret

volumes:
  frigate-config:
